# Generated by Django 5.2.6 on 2026-01-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_comment_depth'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='descendants_count',
            field=models.IntegerField(default=0),
        ),
    ]
