# Generated by Django 5.2.6 on 2026-01-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_comment_descendants_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
        migrations.AddField(
            model_name='comment',
            name='path',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
