# Generated by Django 5.2.6 on 2026-01-31 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_remove_comment_parent_comment_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='theme',
        ),
    ]
