# Generated by Django 5.2.6 on 2026-01-31 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_remove_post_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='backend.comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='descendants_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='path',
            field=models.TextField(blank=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', 'path'], name='backend_com_post_id_3e0b68_idx'),
        ),
    ]
